from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


GENERATED_MARKER = "<!-- Generated by memory-dream. Edit the source ZK wiki instead. -->"
DEFAULT_DREAM_ROOT = Path.home() / ".memory-dream"


class MemoryDreamError(Exception):
    """User-facing command failure."""


@dataclass(frozen=True)
class Project:
    id: str
    name: str
    root: Path
    source: Path
    artifact: Path
    cache: Path
    created_at: str
    updated_at: str


def main(argv: list[str] | None = None) -> int:
    parser = make_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except MemoryDreamError as exc:
        print(f"memory-dream: error: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("memory-dream: interrupted", file=sys.stderr)
        return 130


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="memory-dream")
    parser.add_argument("--project-root", type=Path, help="Resolve or register this project instead of cwd.")
    parser.add_argument("--dream-root", type=Path, help="Use a non-default management root.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    for name, func, help_text in [
        ("init", cmd_init, "register the current project"),
        ("where", cmd_where, "print the current project binding"),
        ("open", cmd_open, "print the source wiki path"),
        ("build", cmd_build, "build Markdown artifacts"),
        ("show", cmd_show, "print artifact/Memory.md"),
        ("check", cmd_check, "delegate graph checks to zk-lsp"),
    ]:
        sub = subparsers.add_parser(name, help=help_text)
        sub.set_defaults(func=func)

    return parser


def cmd_init(args: argparse.Namespace) -> int:
    dream_root = resolve_dream_root(args)
    project_root = resolve_project_root(args.project_root, dream_root, for_init=True)
    registry = load_registry(dream_root)
    existing = find_project_by_root(registry, project_root)
    if existing is None and args.project_root is None:
        existing = find_project_containing_path(registry, Path.cwd().resolve())
    if existing:
        print_binding(existing)
        return 0

    project = new_project(dream_root, project_root)
    project_dir = dream_root / "projects" / project.id

    ensure_new_project_dirs(project)
    try:
        run_zk_lsp(["init"], cwd=project.source)
    except Exception:
        if not any(project_dir.iterdir()):
            project_dir.rmdir()
        raise

    now = iso_now()
    project = Project(
        id=project.id,
        name=project.name,
        root=project.root,
        source=project.source,
        artifact=project.artifact,
        cache=project.cache,
        created_at=now,
        updated_at=now,
    )
    registry.append(project)
    write_registry(dream_root, registry)
    print_binding(project)
    return 0


def cmd_where(args: argparse.Namespace) -> int:
    project = require_project(args)
    print_binding(project)
    return 0


def cmd_open(args: argparse.Namespace) -> int:
    project = require_project(args)
    print(project.source)
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    project = require_project(args)
    require_source_wiki(project)
    run_zk_lsp(["--wiki-root", str(project.source), "generate"], cwd=project.source)
    build_artifacts(project)
    print(project.artifact)
    return 0


def cmd_show(args: argparse.Namespace) -> int:
    project = require_project(args)
    memory_file = project.artifact / "Memory.md"
    if not memory_file.exists():
        raise MemoryDreamError(f"artifact missing: {memory_file}; run `memory-dream build`")
    print(memory_file.read_text(encoding="utf-8"), end="")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    project = require_project(args)
    require_source_wiki(project)
    return run_zk_lsp(["--wiki-root", str(project.source), "check"], cwd=project.source, raise_on_failure=False)


def resolve_dream_root(args: argparse.Namespace) -> Path:
    return (args.dream_root or DEFAULT_DREAM_ROOT).expanduser().resolve()


def resolve_project_root(project_root: Path | None, dream_root: Path, *, for_init: bool = False) -> Path:
    if project_root is not None:
        return project_root.expanduser().resolve()

    cwd = Path.cwd().resolve()
    git_root = find_git_root(cwd)
    if git_root is not None:
        return git_root

    if not for_init:
        registry = load_registry(dream_root)
        ancestor = find_project_containing_path(registry, cwd)
        if ancestor is not None:
            return ancestor.root

    return cwd


def find_git_root(start: Path) -> Path | None:
    for path in [start, *start.parents]:
        if (path / ".git").exists():
            return path
    return None


def project_id_for(root: Path) -> str:
    name = slugify(root.name) or "project"
    digest = hashlib.sha1(str(root).encode("utf-8")).hexdigest()[:6]
    return f"{name}-{digest}"


def new_project(dream_root: Path, root: Path) -> Project:
    project_id = project_id_for(root)
    base = dream_root / "projects" / project_id
    return Project(
        id=project_id,
        name=root.name or project_id,
        root=root,
        source=base / "source",
        artifact=base / "artifact",
        cache=base / "cache",
        created_at="",
        updated_at="",
    )


def ensure_new_project_dirs(project: Project) -> None:
    project_dir = project.source.parent
    project_dir.mkdir(parents=True, exist_ok=True)
    if project.source.exists() and any(project.source.iterdir()):
        raise MemoryDreamError(f"source exists but is not empty for an unregistered project: {project.source}")
    project.source.mkdir(parents=True, exist_ok=True)
    project.artifact.mkdir(parents=True, exist_ok=True)
    project.cache.mkdir(parents=True, exist_ok=True)


def require_source_wiki(project: Project) -> None:
    missing = [p for p in [project.source / "index.typ", project.source / "note"] if not p.exists()]
    if missing:
        paths = ", ".join(str(p) for p in missing)
        raise MemoryDreamError(f"source wiki missing expected files for {project.root}: {paths}")


def run_zk_lsp(args: list[str], *, cwd: Path, raise_on_failure: bool = True) -> int:
    exe = shutil.which("zk-lsp")
    if exe is None:
        raise MemoryDreamError("missing `zk-lsp`; install it and ensure it is on PATH")
    try:
        completed = subprocess.run([exe, *args], cwd=cwd, check=False)
    except OSError as exc:
        raise MemoryDreamError(f"failed to run zk-lsp in {cwd}: {exc}") from exc
    if raise_on_failure and completed.returncode != 0:
        raise MemoryDreamError(f"`zk-lsp {' '.join(args)}` failed in {cwd} with exit code {completed.returncode}")
    return completed.returncode


def load_registry(dream_root: Path) -> list[Project]:
    path = dream_root / "dream.toml"
    if not path.exists():
        return []
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        raise MemoryDreamError(f"invalid registry {path}: {exc}") from exc
    if data.get("version") != 1:
        raise MemoryDreamError(f"invalid registry {path}: version must be 1")
    projects = data.get("project", [])
    if not isinstance(projects, list):
        raise MemoryDreamError(f"invalid registry {path}: project must be an array")

    parsed: list[Project] = []
    seen_ids: set[str] = set()
    seen_roots: set[Path] = set()
    for item in projects:
        try:
            project = Project(
                id=str(item["id"]),
                name=str(item["name"]),
                root=Path(str(item["root"])).expanduser().resolve(),
                source=Path(str(item["source"])).expanduser().resolve(),
                artifact=Path(str(item["artifact"])).expanduser().resolve(),
                cache=Path(str(item["cache"])).expanduser().resolve(),
                created_at=str(item.get("created_at", "")),
                updated_at=str(item.get("updated_at", "")),
            )
        except KeyError as exc:
            raise MemoryDreamError(f"invalid registry {path}: missing project field {exc.args[0]}") from exc
        validate_managed_paths(dream_root, project, path)
        if project.id in seen_ids:
            raise MemoryDreamError(f"invalid registry {path}: duplicate project id {project.id}")
        if project.root in seen_roots:
            raise MemoryDreamError(f"invalid registry {path}: duplicate project root {project.root}")
        seen_ids.add(project.id)
        seen_roots.add(project.root)
        parsed.append(project)
    return parsed


def validate_managed_paths(dream_root: Path, project: Project, registry_path: Path) -> None:
    expected_base = (dream_root / "projects" / project.id).resolve()
    expected_paths = {
        "source": expected_base / "source",
        "artifact": expected_base / "artifact",
        "cache": expected_base / "cache",
    }
    actual_paths = {
        "source": project.source,
        "artifact": project.artifact,
        "cache": project.cache,
    }
    for field, expected in expected_paths.items():
        actual = actual_paths[field]
        if actual != expected:
            raise MemoryDreamError(
                f"invalid registry {registry_path}: project {project.id} {field} must be {expected}, got {actual}"
            )


def write_registry(dream_root: Path, projects: list[Project]) -> None:
    dream_root.mkdir(parents=True, exist_ok=True)
    path = dream_root / "dream.toml"
    lines = ["version = 1", ""]
    for project in sorted(projects, key=lambda p: p.id):
        lines.extend(
            [
                "[[project]]",
                f'id = "{toml_escape(project.id)}"',
                f'name = "{toml_escape(project.name)}"',
                f'root = "{toml_escape(str(project.root))}"',
                f'source = "{toml_escape(str(project.source))}"',
                f'artifact = "{toml_escape(str(project.artifact))}"',
                f'cache = "{toml_escape(str(project.cache))}"',
                f'created_at = "{toml_escape(project.created_at)}"',
                f'updated_at = "{toml_escape(project.updated_at)}"',
                "",
            ]
        )
    path.write_text("\n".join(lines), encoding="utf-8")


def toml_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def find_project_by_root(projects: Iterable[Project], root: Path) -> Project | None:
    for project in projects:
        if project.root == root:
            return project
    return None


def find_project_containing_path(projects: Iterable[Project], path: Path) -> Project | None:
    candidates = []
    for project in projects:
        try:
            path.relative_to(project.root)
        except ValueError:
            continue
        candidates.append(project)
    if not candidates:
        return None
    return max(candidates, key=lambda p: len(p.root.parts))


def require_project(args: argparse.Namespace) -> Project:
    dream_root = resolve_dream_root(args)
    project_root = resolve_project_root(args.project_root, dream_root)
    registry = load_registry(dream_root)
    project = find_project_by_root(registry, project_root)
    if project is None and args.project_root is None:
        project = find_project_containing_path(registry, Path.cwd().resolve())
    if project is None:
        raise MemoryDreamError(f"unregistered project: {project_root}; run `memory-dream init`")
    return project


def print_binding(project: Project) -> None:
    print(f"project:  {project.root}")
    print(f"id:       {project.id}")
    print(f"source:   {project.source}")
    print(f"artifact: {project.artifact}")


def build_artifacts(project: Project) -> None:
    index_path = project.source / "index.typ"
    note_dir = project.source / "note"
    notes = sorted(note_dir.glob("*.typ"))
    note_infos = [parse_note_info(path) for path in notes]
    link_map = {
        info["id"]: {
            "title": info["title"],
            "filename": artifact_name(info["id"], info["title"]),
        }
        for info in note_infos
    }

    clean_artifact_dir(project)
    memory_dir = project.artifact / "memory"
    memory_dir.mkdir(parents=True, exist_ok=True)

    index_text = index_path.read_text(encoding="utf-8")
    (project.artifact / "Memory.md").write_text(
        normalize_typst(
            index_text,
            source="index.typ",
            link_map=link_map,
            note_id=None,
            title=None,
            link_prefix="memory/",
        ),
        encoding="utf-8",
    )

    for path, info in zip(notes, note_infos, strict=True):
        rel_source = f"note/{path.name}"
        output = memory_dir / artifact_name(info["id"], info["title"])
        output.write_text(
            normalize_typst(
                path.read_text(encoding="utf-8"),
                source=rel_source,
                link_map=link_map,
                note_id=info["id"],
                title=info["title"],
                link_prefix="",
            ),
            encoding="utf-8",
        )


def clean_artifact_dir(project: Project) -> None:
    artifact = project.artifact
    expected = (project.source.parent / "artifact").resolve()
    if artifact.resolve() != expected:
        raise MemoryDreamError(f"refusing to clean unmanaged artifact directory: {artifact}")
    artifact.mkdir(parents=True, exist_ok=True)
    for path in artifact.iterdir():
        if path.is_dir():
            shutil.rmtree(path)
        elif path.is_file():
            path.unlink()


def parse_note_info(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"^=\s+(.+?)\s+<(\d{10})>\s*$", text, flags=re.MULTILINE)
    if not match:
        raise MemoryDreamError(f"invalid note header: {path}")
    return {"title": match.group(1).strip(), "id": match.group(2)}


def artifact_name(note_id: str, title: str) -> str:
    return f"{note_id}-{slugify(title) or 'note'}.md"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower()).strip("-")
    return slug or re.sub(r"[^0-9a-zA-Z]+", "-", value.strip()).strip("-").lower()


def normalize_typst(
    text: str,
    *,
    source: str,
    link_map: dict[str, dict[str, str]],
    note_id: str | None,
    title: str | None,
    link_prefix: str,
) -> str:
    metadata, body = extract_metadata(text)
    tags, body_lines = extract_tags_and_body(body.splitlines())
    body_text = "\n".join(normalize_line(line, link_map, link_prefix) for line in body_lines).strip()
    frontmatter = render_frontmatter(metadata, source=source, tags=tags, note_id=note_id, title=title)
    return f"{GENERATED_MARKER}\n\n{frontmatter}\n\n{body_text}\n"


def extract_metadata(text: str) -> tuple[str, str]:
    lines = text.splitlines()
    start = None
    fence = None
    end = None
    for idx, line in enumerate(lines):
        stripped = line.strip()
        if start is None and stripped.startswith("#let zk-metadata") and "toml(bytes(" in stripped:
            start = idx
            continue
        if start is not None and fence is None and stripped == "```toml":
            fence = idx
            continue
        if fence is not None and stripped.startswith("```"):
            end = idx
            break
    if start is None or fence is None or end is None:
        return "", "\n".join(lines)
    metadata = "\n".join(lines[fence + 1 : end])
    body_lines = lines[:start] + lines[end + 1 :]
    return metadata, "\n".join(body_lines)


def extract_tags_and_body(lines: list[str]) -> tuple[list[str], list[str]]:
    tags: list[str] = []
    body: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#import "):
            continue
        if stripped.startswith("#show:"):
            continue
        if stripped.startswith("#status_tag("):
            continue
        tag_matches = re.findall(r"#tag\.([A-Za-z0-9_-]+)", line)
        if tag_matches and stripped.replace(" ", "") == "".join(f"#tag.{tag}" for tag in tag_matches):
            tags.extend(tag_matches)
            continue
        if tag_matches:
            tags.extend(tag_matches)
            line = re.sub(r"#tag\.[A-Za-z0-9_-]+", "", line).rstrip()
            if not line.strip():
                continue
        body.append(line)
    return sorted(set(tags)), body


def normalize_line(line: str, link_map: dict[str, dict[str, str]], link_prefix: str) -> str:
    heading = re.match(r"^(=+)\s+(.+)$", line)
    if heading:
        level = len(heading.group(1))
        text = re.sub(r"\s+<\d{10}>\s*$", "", heading.group(2)).strip()
        return f"{'#' * level} {replace_refs(text, link_map, link_prefix)}"
    return replace_refs(line, link_map, link_prefix)


def replace_refs(line: str, link_map: dict[str, dict[str, str]], link_prefix: str) -> str:
    def repl(match: re.Match[str]) -> str:
        ref = match.group(1)
        target = link_map.get(ref)
        if target is None:
            return f"@{ref}"
        return f"[{target['title']} @{ref}]({link_prefix}{target['filename']})"

    return re.sub(r"@(\d{10})", repl, line)


def render_frontmatter(
    metadata: str,
    *,
    source: str,
    tags: list[str],
    note_id: str | None,
    title: str | None,
) -> str:
    lines = ["+++"]
    if note_id:
        lines.append(f'id = "{toml_escape(note_id)}"')
    if title:
        lines.append(f'title = "{toml_escape(title)}"')
    lines.append(f'source = "{toml_escape(source)}"')
    if tags:
        lines.append("tags = [" + ", ".join(f'"{toml_escape(tag)}"' for tag in tags) + "]")
    metadata_lines = [line.rstrip() for line in metadata.splitlines() if line.strip()]
    if metadata_lines:
        lines.extend(metadata_lines)
    lines.append("+++")
    return "\n".join(lines)


def iso_now() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
