from __future__ import annotations

import argparse
import contextlib
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable

try:
    import fcntl
except ImportError:  # pragma: no cover - Windows fallback
    fcntl = None


GENERATED_MARKER = "<!-- Generated by memory-dream. Edit the source ZK wiki instead. -->"
DEFAULT_DREAM_ROOT = Path.home() / ".memory-dream"
PROJECT_ID_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?-[0-9a-f]{6}$")
RESERVED_FRONTMATTER_KEYS = {"id", "title", "source", "tags"}


class MemoryDreamError(Exception):
    """User-facing command failure."""


@dataclass(frozen=True)
class Project:
    id: str
    name: str
    root: Path
    source: Path
    artifact: Path
    cache: Path
    created_at: str
    updated_at: str


def main(argv: list[str] | None = None) -> int:
    parser = make_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except MemoryDreamError as exc:
        print(f"memory-dream: error: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("memory-dream: interrupted", file=sys.stderr)
        return 130


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="memory-dream")
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "--project-root",
        type=Path,
        default=argparse.SUPPRESS,
        help="Resolve or register this project instead of cwd.",
    )
    common.add_argument(
        "--dream-root",
        type=Path,
        default=argparse.SUPPRESS,
        help="Use a non-default management root.",
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=argparse.SUPPRESS,
        help="Resolve or register this project instead of cwd.",
    )
    parser.add_argument(
        "--dream-root",
        type=Path,
        default=argparse.SUPPRESS,
        help="Use a non-default management root.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    for name, func, help_text in [
        ("init", cmd_init, "register the current project"),
        ("where", cmd_where, "print the current project binding"),
        ("open", cmd_open, "print the source wiki path"),
        ("status", cmd_status, "print project memory status"),
        ("list", cmd_list, "list source notes"),
        ("new", cmd_new, "create a source note via zk-lsp"),
        ("edit", cmd_edit, "print or open a source note path"),
        ("link", cmd_link, "link a source note from index.typ"),
        ("build", cmd_build, "build Markdown artifacts"),
        ("context", cmd_context, "print AI-consumable project memory context"),
        ("show", cmd_show, "print artifact/Memory.md"),
        ("check", cmd_check, "delegate graph checks to zk-lsp"),
    ]:
        sub = subparsers.add_parser(name, parents=[common], help=help_text)
        if name in {"status", "list"}:
            sub.add_argument(
                "--format",
                choices=["text", "json"],
                default="text",
                help="Output format.",
            )
        if name == "new":
            sub.add_argument("--title", required=True, help="Note title.")
            sub.add_argument("--id", help="Custom 10-digit note ID.")
            sub.add_argument(
                "--kind",
                required=True,
                choices=["decision", "experience"],
                help="Memory note kind.",
            )
            sub.add_argument("--content", default="", help="Initial note content.")
            sub.add_argument("--link", action="store_true", help="Link the new note from index.typ.")
            sub.add_argument("--build", action="store_true", help="Build artifacts after creating the note.")
        if name == "edit":
            sub.add_argument("id", help="10-digit note ID.")
            sub.add_argument("--editor", action="store_true", help="Open the note with $EDITOR instead of printing the path.")
        if name == "link":
            sub.add_argument("id", help="10-digit note ID.")
            sub.add_argument("--section", help="Reserved for section-aware linking; currently appends to index.typ.")
            sub.add_argument("--build", action="store_true", help="Build artifacts after linking the note.")
        if name == "context":
            sub.add_argument(
                "--all",
                action="store_true",
                help="Include every generated note artifact instead of only Memory.md references.",
            )
            sub.add_argument(
                "--max-notes",
                type=int,
                default=20,
                help="Maximum referenced notes to include unless --all is set.",
            )
        sub.set_defaults(func=func)

    return parser


def cmd_init(args: argparse.Namespace) -> int:
    dream_root = resolve_dream_root(args)
    project_arg = getattr(args, "project_root", None)
    project_root = resolve_project_root(project_arg, dream_root, for_init=True)
    validate_project_root(project_root)
    with registry_lock(dream_root):
        registry = load_registry(dream_root)
        existing = find_project_by_root(registry, project_root)
        if existing is None and project_arg is None and find_git_root(Path.cwd().resolve()) is None:
            existing = find_project_containing_path(registry, Path.cwd().resolve())
        if existing:
            print_binding(existing)
            return 0

        project = new_project(dream_root, project_root)

        ensure_new_project_dirs(project)
        try:
            run_zk_lsp(["init"], cwd=project.source)
        except Exception:
            remove_unregistered_project_dir(dream_root, project)
            raise

        now = iso_now()
        project = Project(
            id=project.id,
            name=project.name,
            root=project.root,
            source=project.source,
            artifact=project.artifact,
            cache=project.cache,
            created_at=now,
            updated_at=now,
        )
        registry.append(project)
        write_registry(dream_root, registry)
        print_binding(project)
    return 0


def cmd_where(args: argparse.Namespace) -> int:
    project = require_project(args)
    print_binding(project)
    return 0


def cmd_open(args: argparse.Namespace) -> int:
    project = require_project(args)
    print(project.source)
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    project = require_project(args)
    status = project_status(project)
    if getattr(args, "format") == "json":
        print(json.dumps(status, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print_status(status)
    return 0


def cmd_list(args: argparse.Namespace) -> int:
    project = require_project(args)
    require_source_wiki(project)
    notes = list_note_summaries(project)
    if getattr(args, "format") == "json":
        print(json.dumps(notes, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        for note in notes:
            print(f"{note['id']}  {note['title']}")
    return 0


def cmd_new(args: argparse.Namespace) -> int:
    project = require_project(args)
    require_source_wiki(project)
    payload = {
        "title": args.title,
        "content": args.content,
        "metadata": {
            "keywords": [args.kind],
            "relation": "active",
        },
    }
    note_id = getattr(args, "id", None) or next_note_id(project)
    validate_note_id(note_id)
    if (project.source / "note" / f"{note_id}.typ").exists():
        raise MemoryDreamError(f"note already exists: {note_id}")
    output = run_zk_lsp_capture(
        ["--wiki-root", str(project.source), "new", "--id", note_id, "--json"],
        cwd=project.source,
        input_text=json.dumps(payload, ensure_ascii=False),
    )
    note_path = Path(output.strip()).expanduser()
    if not note_path.is_absolute():
        note_path = (project.source / note_path).resolve()
    note_id = note_path.stem
    print(f"created: {note_id}")
    print(f"source:  {note_path}")
    if getattr(args, "link", False):
        link_note(project, note_id)
        print("linked:  true")
    else:
        print("linked:  false")
    if getattr(args, "build", False):
        build_project(project)
        print(f"artifact: {project.artifact}")
    else:
        print("stale:   true")
        print("next:    memory-dream build")
    return 0


def cmd_edit(args: argparse.Namespace) -> int:
    project = require_project(args)
    path = note_path_for_id(project, args.id)
    if getattr(args, "editor", False):
        editor = os.environ.get("EDITOR")
        if not editor:
            raise MemoryDreamError("$EDITOR is not set")
        completed = subprocess.run([editor, str(path)], check=False)
        return completed.returncode
    print(path)
    return 0


def cmd_link(args: argparse.Namespace) -> int:
    project = require_project(args)
    if getattr(args, "section", None):
        raise MemoryDreamError("--section is reserved but not implemented yet")
    note = note_info_by_id(project, args.id)
    link_note(project, note["id"])
    print(f"linked: {note['id']}  {note['title']}")
    if getattr(args, "build", False):
        build_project(project)
        print(f"artifact: {project.artifact}")
    else:
        print("stale:  true")
        print("next:   memory-dream build")
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    project = require_project(args)
    build_project(project)
    print(project.artifact)
    return 0


def cmd_context(args: argparse.Namespace) -> int:
    project = require_project(args)
    memory_file = project.artifact / "Memory.md"
    if not memory_file.exists():
        raise MemoryDreamError(f"artifact missing: {memory_file}; run `memory-dream build`")
    ensure_context_artifacts_current(project)
    max_notes = getattr(args, "max_notes", 20)
    if max_notes < 0:
        raise MemoryDreamError("--max-notes must be non-negative")
    print(render_context(project, include_all=getattr(args, "all", False), max_notes=max_notes), end="")
    return 0


def cmd_show(args: argparse.Namespace) -> int:
    project = require_project(args)
    memory_file = project.artifact / "Memory.md"
    if not memory_file.exists():
        raise MemoryDreamError(f"artifact missing: {memory_file}; run `memory-dream build`")
    print(memory_file.read_text(encoding="utf-8"), end="")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    project = require_project(args)
    require_source_wiki(project)
    return run_zk_lsp(["--wiki-root", str(project.source), "check"], cwd=project.source, raise_on_failure=False)


def resolve_dream_root(args: argparse.Namespace) -> Path:
    return (getattr(args, "dream_root", None) or DEFAULT_DREAM_ROOT).expanduser().resolve()


def resolve_project_root(project_root: Path | None, dream_root: Path, *, for_init: bool = False) -> Path:
    if project_root is not None:
        resolved = project_root.expanduser().resolve()
        validate_project_root(resolved)
        return resolved

    cwd = Path.cwd().resolve()
    git_root = find_git_root(cwd)
    if git_root is not None:
        return git_root

    if not for_init:
        registry = load_registry(dream_root)
        ancestor = find_project_containing_path(registry, cwd)
        if ancestor is not None:
            return ancestor.root

    return cwd


def validate_project_root(project_root: Path) -> None:
    if not project_root.exists():
        raise MemoryDreamError(f"project root does not exist: {project_root}")
    if not project_root.is_dir():
        raise MemoryDreamError(f"project root is not a directory: {project_root}")


def find_git_root(start: Path) -> Path | None:
    for path in [start, *start.parents]:
        if (path / ".git").exists():
            return path
    return None


def project_id_for(root: Path) -> str:
    name = slugify(root.name) or "project"
    digest = hashlib.sha1(str(root).encode("utf-8")).hexdigest()[:6]
    return f"{name}-{digest}"


def validate_project_id(project_id: str, registry_path: Path) -> None:
    if not PROJECT_ID_RE.fullmatch(project_id):
        raise MemoryDreamError(f"invalid registry {registry_path}: invalid project id {project_id!r}")


def new_project(dream_root: Path, root: Path) -> Project:
    project_id = project_id_for(root)
    base = dream_root / "projects" / project_id
    return Project(
        id=project_id,
        name=root.name or project_id,
        root=root,
        source=base / "source",
        artifact=base / "artifact",
        cache=base / "cache",
        created_at="",
        updated_at="",
    )


def ensure_new_project_dirs(project: Project) -> None:
    validate_project_id(project.id, Path("runtime project"))
    projects_root = project.source.parent.parent
    project_dir = project.source.parent
    if projects_root.exists() and projects_root.is_symlink():
        raise MemoryDreamError(f"projects directory must not be a symlink: {projects_root}")
    projects_root.mkdir(parents=True, exist_ok=True)
    if project_dir.exists():
        if project_dir.is_symlink() or not project_dir.is_dir():
            raise MemoryDreamError(f"project directory is not a plain directory: {project_dir}")
        if any(project_dir.iterdir()):
            raise MemoryDreamError(f"project directory exists but is not empty for an unregistered project: {project_dir}")
    else:
        project_dir.mkdir()
    try:
        project_dir.resolve().relative_to(projects_root.resolve())
    except ValueError as exc:
        raise MemoryDreamError(f"project directory escapes managed projects root: {project_dir}") from exc
    if project.source.exists() and any(project.source.iterdir()):
        raise MemoryDreamError(f"source exists but is not empty for an unregistered project: {project.source}")
    project.source.mkdir(parents=True, exist_ok=True)
    project.artifact.mkdir(parents=True, exist_ok=True)
    project.cache.mkdir(parents=True, exist_ok=True)


def require_source_wiki(project: Project) -> None:
    missing = [p for p in [project.source / "index.typ", project.source / "note"] if not p.exists()]
    if missing:
        paths = ", ".join(str(p) for p in missing)
        raise MemoryDreamError(f"source wiki missing expected files for {project.root}: {paths}")


def build_project(project: Project) -> None:
    require_source_wiki(project)
    run_zk_lsp(["--wiki-root", str(project.source), "generate"], cwd=project.source)
    with file_lock(project.source.parent / ".build.lock"):
        build_artifacts(project)


def remove_unregistered_project_dir(dream_root: Path, project: Project) -> None:
    projects_root = (dream_root / "projects").resolve()
    project_dir = project.source.parent.resolve()
    if project_dir.name != project.id:
        return
    try:
        project_dir.relative_to(projects_root)
    except ValueError:
        return
    shutil.rmtree(project_dir, ignore_errors=True)


def run_zk_lsp(args: list[str], *, cwd: Path, raise_on_failure: bool = True) -> int:
    exe = shutil.which("zk-lsp")
    if exe is None:
        raise MemoryDreamError("missing `zk-lsp`; install it and ensure it is on PATH")
    try:
        completed = subprocess.run([exe, *args], cwd=cwd, check=False)
    except OSError as exc:
        raise MemoryDreamError(f"failed to run zk-lsp in {cwd}: {exc}") from exc
    if raise_on_failure and completed.returncode != 0:
        raise MemoryDreamError(f"`zk-lsp {' '.join(args)}` failed in {cwd} with exit code {completed.returncode}")
    return completed.returncode


def run_zk_lsp_capture(args: list[str], *, cwd: Path, input_text: str | None = None) -> str:
    exe = shutil.which("zk-lsp")
    if exe is None:
        raise MemoryDreamError("missing `zk-lsp`; install it and ensure it is on PATH")
    try:
        completed = subprocess.run(
            [exe, *args],
            cwd=cwd,
            input=input_text,
            text=True,
            capture_output=True,
            check=False,
        )
    except OSError as exc:
        raise MemoryDreamError(f"failed to run zk-lsp in {cwd}: {exc}") from exc
    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip()
        suffix = f": {detail}" if detail else ""
        raise MemoryDreamError(f"`zk-lsp {' '.join(args)}` failed in {cwd} with exit code {completed.returncode}{suffix}")
    return completed.stdout


def load_registry(dream_root: Path) -> list[Project]:
    path = dream_root / "dream.toml"
    if not path.exists():
        return []
    try:
        raw = path.read_text(encoding="utf-8")
        data = tomllib.loads(raw)
    except (OSError, UnicodeDecodeError) as exc:
        raise MemoryDreamError(f"invalid or unreadable registry {path}: {exc}") from exc
    except tomllib.TOMLDecodeError as exc:
        raise MemoryDreamError(f"invalid registry {path}: {exc}") from exc
    if data.get("version") != 1:
        raise MemoryDreamError(f"invalid registry {path}: version must be 1")
    projects = data.get("project", [])
    if not isinstance(projects, list):
        raise MemoryDreamError(f"invalid registry {path}: project must be an array")

    parsed: list[Project] = []
    seen_ids: set[str] = set()
    seen_roots: set[Path] = set()
    for item in projects:
        if not isinstance(item, Mapping):
            raise MemoryDreamError(f"invalid registry {path}: project entries must be tables")
        try:
            project = Project(
                id=str(item["id"]),
                name=str(item["name"]),
                root=Path(str(item["root"])).expanduser().resolve(),
                source=Path(str(item["source"])).expanduser().resolve(),
                artifact=Path(str(item["artifact"])).expanduser().resolve(),
                cache=Path(str(item["cache"])).expanduser().resolve(),
                created_at=str(item.get("created_at", "")),
                updated_at=str(item.get("updated_at", "")),
            )
        except KeyError as exc:
            raise MemoryDreamError(f"invalid registry {path}: missing project field {exc.args[0]}") from exc
        validate_project_id(project.id, path)
        validate_managed_paths(dream_root, project, path)
        if project.id in seen_ids:
            raise MemoryDreamError(f"invalid registry {path}: duplicate project id {project.id}")
        if project.root in seen_roots:
            raise MemoryDreamError(f"invalid registry {path}: duplicate project root {project.root}")
        seen_ids.add(project.id)
        seen_roots.add(project.root)
        parsed.append(project)
    return parsed


def validate_managed_paths(dream_root: Path, project: Project, registry_path: Path) -> None:
    projects_root = (dream_root / "projects").resolve()
    expected_base = (projects_root / project.id).resolve()
    try:
        expected_base.relative_to(projects_root)
    except ValueError as exc:
        raise MemoryDreamError(f"invalid registry {registry_path}: project {project.id} escapes projects directory") from exc
    expected_paths = {
        "source": expected_base / "source",
        "artifact": expected_base / "artifact",
        "cache": expected_base / "cache",
    }
    actual_paths = {
        "source": project.source,
        "artifact": project.artifact,
        "cache": project.cache,
    }
    for field, expected in expected_paths.items():
        actual = actual_paths[field]
        if actual != expected:
            raise MemoryDreamError(
                f"invalid registry {registry_path}: project {project.id} {field} must be {expected}, got {actual}"
            )


def write_registry(dream_root: Path, projects: list[Project]) -> None:
    dream_root.mkdir(parents=True, exist_ok=True)
    path = dream_root / "dream.toml"
    lines = ["version = 1", ""]
    for project in sorted(projects, key=lambda p: p.id):
        lines.extend(
            [
                "[[project]]",
                f'id = "{toml_escape(project.id)}"',
                f'name = "{toml_escape(project.name)}"',
                f'root = "{toml_escape(str(project.root))}"',
                f'source = "{toml_escape(str(project.source))}"',
                f'artifact = "{toml_escape(str(project.artifact))}"',
                f'cache = "{toml_escape(str(project.cache))}"',
                f'created_at = "{toml_escape(project.created_at)}"',
                f'updated_at = "{toml_escape(project.updated_at)}"',
                "",
            ]
        )
    data = "\n".join(lines)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=dream_root, prefix=".dream.", suffix=".tmp", delete=False) as file:
        tmp_path = Path(file.name)
        file.write(data)
        file.flush()
        os.fsync(file.fileno())
    try:
        tmp_path.replace(path)
        fsync_directory(dream_root)
    except Exception:
        tmp_path.unlink(missing_ok=True)
        raise


def fsync_directory(path: Path) -> None:
    if not hasattr(os, "O_DIRECTORY"):
        return
    try:
        fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY)
    except OSError:
        return
    try:
        os.fsync(fd)
    finally:
        os.close(fd)


@contextlib.contextmanager
def registry_lock(dream_root: Path):
    dream_root.mkdir(parents=True, exist_ok=True)
    with file_lock(dream_root / ".dream.lock"):
        yield


@contextlib.contextmanager
def file_lock(lock_path: Path):
    if fcntl is None:
        yield
        return
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("a+", encoding="utf-8") as lock_file:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lock_file.fileno(), fcntl.LOCK_UN)


def toml_escape(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)[1:-1]


def find_project_by_root(projects: Iterable[Project], root: Path) -> Project | None:
    for project in projects:
        if project.root == root:
            return project
    return None


def find_project_containing_path(projects: Iterable[Project], path: Path) -> Project | None:
    candidates = []
    for project in projects:
        try:
            path.relative_to(project.root)
        except ValueError:
            continue
        candidates.append(project)
    if not candidates:
        return None
    return max(candidates, key=lambda p: len(p.root.parts))


def require_project(args: argparse.Namespace) -> Project:
    dream_root = resolve_dream_root(args)
    project_arg = getattr(args, "project_root", None)
    project_root = resolve_project_root(project_arg, dream_root)
    registry = load_registry(dream_root)
    project = find_project_by_root(registry, project_root)
    if project is None and project_arg is None and find_git_root(Path.cwd().resolve()) is None:
        project = find_project_containing_path(registry, Path.cwd().resolve())
    if project is None:
        raise MemoryDreamError(f"unregistered project: {project_root}; run `memory-dream init`")
    return project


def print_binding(project: Project) -> None:
    print(f"project:  {project.root}")
    print(f"id:       {project.id}")
    print(f"source:   {project.source}")
    print(f"artifact: {project.artifact}")


def project_status(project: Project) -> dict[str, object]:
    source_ok = (project.source / "index.typ").exists() and (project.source / "note").is_dir()
    memory_file = project.artifact / "Memory.md"
    built = memory_file.exists()
    notes = list_note_summaries(project) if source_ok else []
    linked_ids = linked_note_ids(project) if (project.source / "index.typ").exists() else set()
    note_ids = {str(note["id"]) for note in notes}
    stale_reason = context_stale_reason(project) if built and source_ok else None
    return {
        "registered": True,
        "built": built,
        "stale": stale_reason is not None or (source_ok and not built),
        "stale_reason": stale_reason,
        "project": str(project.root),
        "id": project.id,
        "source": str(project.source),
        "artifact": str(project.artifact),
        "notes": len(notes),
        "linked": len(note_ids & linked_ids),
        "unlinked": len(note_ids - linked_ids),
    }


def print_status(status: Mapping[str, object]) -> None:
    for key in [
        "project",
        "id",
        "source",
        "artifact",
        "registered",
        "built",
        "stale",
        "stale_reason",
        "notes",
        "linked",
        "unlinked",
    ]:
        value = status.get(key)
        if value is not None:
            print(f"{key}: {value}")


def list_note_summaries(project: Project) -> list[dict[str, str]]:
    note_dir = project.source / "note"
    if not note_dir.exists():
        return []
    notes: list[dict[str, str]] = []
    for path in sorted(note_dir.glob("*.typ")):
        note_id = path.stem
        validate_note_id(note_id)
        notes.append(note_info_by_id(project, note_id))
    return notes


def linked_note_ids(project: Project) -> set[str]:
    index_path = project.source / "index.typ"
    if not index_path.exists():
        return set()
    return set(re.findall(r"@(\d{10})", uncommented_typst_text(index_path.read_text(encoding="utf-8"))))


def note_info_by_id(project: Project, note_id: str) -> dict[str, str]:
    validate_note_id(note_id)
    fallback = parse_note_info(note_path_for_id(project, note_id))
    try:
        raw = run_zk_lsp_capture(["--wiki-root", str(project.source), "note-info", note_id], cwd=project.source)
        data = json.loads(raw)
    except (MemoryDreamError, json.JSONDecodeError):
        return fallback
    return {
        "id": str(data.get("id") or fallback["id"]),
        "title": str(data.get("title") or fallback["title"]),
        "path": str(Path(str(data.get("path") or fallback["path"])).expanduser().resolve()),
    }


def note_path_for_id(project: Project, note_id: str) -> Path:
    validate_note_id(note_id)
    path = project.source / "note" / f"{note_id}.typ"
    if not path.exists():
        raise MemoryDreamError(f"note not found: {note_id}")
    return path


def validate_note_id(note_id: str) -> None:
    if not re.fullmatch(r"\d{10}", note_id):
        raise MemoryDreamError(f"invalid note id: {note_id}")


def next_note_id(project: Project) -> str:
    existing = {path.stem for path in (project.source / "note").glob("*.typ")}
    candidate = datetime.now().replace(second=0, microsecond=0)
    for _ in range(1440):
        note_id = candidate.strftime("%y%m%d%H%M")
        if note_id not in existing:
            return note_id
        candidate += timedelta(minutes=1)
    raise MemoryDreamError("could not allocate an unused note id")


def link_note(project: Project, note_id: str) -> None:
    validate_note_id(note_id)
    note_path_for_id(project, note_id)
    index_path = project.source / "index.typ"
    with file_lock(project.source.parent / ".index.lock"):
        text = index_path.read_text(encoding="utf-8")
        if re.search(rf"@{re.escape(note_id)}(?!\d)", uncommented_typst_text(text)):
            return
        suffix = "" if text.endswith("\n") else "\n"
        atomic_write_text(index_path, f"{text}{suffix}- @{note_id}\n")


def uncommented_typst_text(text: str) -> str:
    return "\n".join(line for line in text.splitlines() if not line.lstrip().startswith("//"))


def atomic_write_text(path: Path, text: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
        delete=False,
    ) as file:
        tmp_path = Path(file.name)
        file.write(text)
        file.flush()
        os.fsync(file.fileno())
    try:
        tmp_path.replace(path)
        fsync_directory(path.parent)
    except Exception:
        tmp_path.unlink(missing_ok=True)
        raise


def build_artifacts(project: Project) -> None:
    index_path = project.source / "index.typ"
    note_dir = project.source / "note"
    notes = sorted(note_dir.glob("*.typ"))
    note_infos = [parse_note_info(path) for path in notes]
    validate_note_infos(note_infos)
    link_map = {
        info["id"]: {
            "title": info["title"],
            "filename": artifact_name(info["id"], info["title"]),
        }
        for info in note_infos
    }

    staging = create_artifact_staging_dir(project)
    try:
        memory_dir = staging / "memory"
        memory_dir.mkdir(parents=True, exist_ok=True)

        index_text = index_path.read_text(encoding="utf-8")
        (staging / "Memory.md").write_text(
            normalize_typst(
                index_text,
                source="index.typ",
                link_map=link_map,
                note_id=None,
                title=None,
                link_prefix="memory/",
            ),
            encoding="utf-8",
        )

        for path, info in zip(notes, note_infos, strict=True):
            rel_source = f"note/{path.name}"
            output = memory_dir / artifact_name(info["id"], info["title"])
            output.write_text(
                normalize_typst(
                    path.read_text(encoding="utf-8"),
                    source=rel_source,
                    link_map=link_map,
                    note_id=info["id"],
                    title=info["title"],
                    link_prefix="",
                ),
                encoding="utf-8",
            )
        swap_artifact_dir(project, staging)
    except Exception:
        if staging.exists():
            shutil.rmtree(staging, ignore_errors=True)
        raise


def render_context(project: Project, *, include_all: bool, max_notes: int) -> str:
    memory_file = project.artifact / "Memory.md"
    memory_text = memory_file.read_text(encoding="utf-8")
    note_dir = project.artifact / "memory"
    if include_all:
        note_paths = sorted(note_dir.glob("*.md")) if note_dir.exists() else []
        omitted = 0
    else:
        referenced = extract_memory_links(memory_text)
        if max_notes:
            selected = referenced[:max_notes]
            omitted = max(0, len(referenced) - len(selected))
        else:
            selected = []
            omitted = len(referenced)
        note_paths = [project.artifact / href for href in selected]

    missing = [path for path in note_paths if not path.is_file()]
    if missing:
        paths = ", ".join(str(path) for path in missing)
        raise MemoryDreamError(f"context references missing note artifacts: {paths}; run `memory-dream build`")

    parts = [
        "# Project Memory Context",
        "",
        "## Paths",
        "",
        f"- project-root: `{project.root}`",
        f"- source-root: `{project.source}`",
        f"- artifact-root: `{project.artifact}`",
        f"- memory-entry: `{memory_file}`",
        f"- note-artifacts: `{note_dir}`",
        f"- source-notes: `{project.source / 'note'}`",
        "",
        "## Memory.md",
        "",
        memory_text.rstrip(),
    ]

    if note_paths:
        parts.extend(["", "## Referenced Notes" if not include_all else "## All Notes"])
        for path in note_paths:
            parts.extend(
                [
                    "",
                    f"### {path.name}",
                    "",
                    f"- artifact: `{path}`",
                    f"- source-candidate: `{project.source / 'note' / (note_id_from_artifact(path.name) + '.typ')}`",
                    "",
                    path.read_text(encoding="utf-8").rstrip(),
                ]
            )

    if omitted:
        parts.extend(["", f"<!-- {omitted} referenced note(s) omitted by --max-notes. -->"])

    return "\n".join(parts).rstrip() + "\n"


def ensure_context_artifacts_current(project: Project) -> None:
    reason = context_stale_reason(project)
    if reason is not None:
        raise MemoryDreamError(reason)


def context_stale_reason(project: Project) -> str | None:
    try:
        require_source_wiki(project)
    except MemoryDreamError as exc:
        return str(exc)
    memory_file = project.artifact / "Memory.md"
    if not memory_file.exists():
        return f"artifact missing: {memory_file}; run `memory-dream build`"
    index_path = project.source / "index.typ"
    if source_newer_than_artifact(index_path, memory_file):
        return stale_context_message(index_path, memory_file)

    expected_artifacts: set[str] = set()
    for note_path in sorted((project.source / "note").glob("*.typ")):
        info = parse_note_info(note_path)
        artifact = project.artifact / "memory" / artifact_name(info["id"], info["title"])
        expected_artifacts.add(artifact.name)
        if not artifact.exists():
            return f"artifact stale: missing {artifact}; run `memory-dream build`"
        if source_newer_than_artifact(note_path, artifact):
            return stale_context_message(note_path, artifact)

    artifact_dir = project.artifact / "memory"
    if artifact_dir.exists():
        orphaned = sorted(path for path in artifact_dir.glob("*.md") if path.name not in expected_artifacts)
        if orphaned:
            paths = ", ".join(str(path) for path in orphaned)
            return f"artifact stale: orphaned note artifact(s): {paths}; run `memory-dream build`"
    return None


def source_newer_than_artifact(source: Path, artifact: Path) -> bool:
    return source.stat().st_mtime_ns > artifact.stat().st_mtime_ns


def stale_context_message(source: Path, artifact: Path) -> str:
    return f"artifact stale: {source} is newer than {artifact}; run `memory-dream build`"


def extract_memory_links(text: str) -> list[Path]:
    links: list[Path] = []
    seen: set[Path] = set()
    for match in re.finditer(r"\[[^\]]*]\((memory/[^)\s]+\.md)\)", text):
        href = Path(match.group(1))
        if href.is_absolute() or ".." in href.parts or href.parts[0] != "memory":
            continue
        if href not in seen:
            links.append(href)
            seen.add(href)
    for match in re.finditer(r"(?<!!)\[\[memory/([^\]\s]+\.md)]]", text):
        href = Path("memory") / match.group(1)
        if ".." in href.parts:
            continue
        if href not in seen:
            links.append(href)
            seen.add(href)
    return links


def note_id_from_artifact(filename: str) -> str:
    return filename.split("-", 1)[0]


def validate_artifact_dir(project: Project) -> None:
    validate_project_id(project.id, Path("runtime project"))
    artifact = project.artifact
    expected = (project.source.parent / "artifact").resolve()
    if project.source.parent.name != project.id:
        raise MemoryDreamError(f"refusing to clean artifact for invalid project directory: {project.source.parent}")
    if project.cache.parent != project.source.parent:
        raise MemoryDreamError(f"refusing to clean artifact for inconsistent project paths: {project.id}")
    if artifact.resolve() != expected:
        raise MemoryDreamError(f"refusing to clean unmanaged artifact directory: {artifact}")


def create_artifact_staging_dir(project: Project) -> Path:
    validate_artifact_dir(project)
    project_dir = project.source.parent
    return Path(tempfile.mkdtemp(prefix=".artifact.", suffix=".tmp", dir=project_dir))


def swap_artifact_dir(project: Project, staging: Path) -> None:
    validate_artifact_dir(project)
    artifact = project.artifact
    project_dir = project.source.parent
    backup = project_dir / f".artifact.{os.getpid()}.bak"
    if backup.exists():
        shutil.rmtree(backup)
    try:
        if artifact.exists():
            artifact.rename(backup)
        staging.rename(artifact)
        if backup.exists():
            shutil.rmtree(backup)
    except Exception:
        if not artifact.exists() and backup.exists():
            backup.rename(artifact)
        if staging.exists():
            shutil.rmtree(staging, ignore_errors=True)
        raise


def parse_note_info(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"^=\s*(.*?)\s+<(\d{10})>\s*$", text, flags=re.MULTILINE)
    if not match:
        raise MemoryDreamError(f"invalid note header: {path}")
    return {"title": match.group(1).strip(), "id": match.group(2), "path": str(path)}


def validate_note_infos(note_infos: list[dict[str, str]]) -> None:
    seen_ids: dict[str, str] = {}
    seen_artifacts: dict[str, str] = {}
    for info in note_infos:
        note_id = info["id"]
        path = Path(info["path"])
        if path.stem != note_id:
            raise MemoryDreamError(f"note filename does not match header id: {path} declares <{note_id}>")
        if note_id in seen_ids:
            raise MemoryDreamError(f"duplicate note id {note_id}: {seen_ids[note_id]} and {path}")
        artifact = artifact_name(note_id, info["title"])
        if artifact in seen_artifacts:
            raise MemoryDreamError(f"duplicate artifact filename {artifact}: {seen_artifacts[artifact]} and {path}")
        seen_ids[note_id] = str(path)
        seen_artifacts[artifact] = str(path)


def artifact_name(note_id: str, title: str) -> str:
    return f"{note_id}-{slugify(title) or 'note'}.md"


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.strip().lower()).strip("-")
    return slug or re.sub(r"[^0-9a-zA-Z]+", "-", value.strip()).strip("-").lower()


def normalize_typst(
    text: str,
    *,
    source: str,
    link_map: dict[str, dict[str, str]],
    note_id: str | None,
    title: str | None,
    link_prefix: str,
) -> str:
    metadata, body = extract_metadata(text)
    tags, body_lines = extract_tags_and_body(body.splitlines())
    body_text = "\n".join(normalize_line(line, link_map, link_prefix) for line in body_lines).strip()
    frontmatter = render_frontmatter(metadata, source=source, tags=tags, note_id=note_id, title=title)
    return f"{GENERATED_MARKER}\n\n{frontmatter}\n\n{body_text}\n"


def extract_metadata(text: str) -> tuple[str, str]:
    lines = text.splitlines()
    start = None
    fence = None
    end = None
    expression_end = None
    for idx, line in enumerate(lines):
        stripped = line.strip()
        if start is None and stripped.startswith("#let zk-metadata") and "toml(bytes(" in stripped:
            start = idx
            continue
        if start is not None and fence is None and stripped == "```toml":
            fence = idx
            continue
        if fence is not None and stripped.startswith("```"):
            end = idx
            break
    if start is None or fence is None or end is None:
        return "", "\n".join(lines)
    for idx in range(end + 1, len(lines)):
        stripped = lines[idx].strip()
        if stripped.startswith("#show:"):
            break
        expression_end = idx
        if "))" in stripped:
            break
    metadata = "\n".join(lines[fence + 1 : end])
    drop_end = expression_end if expression_end is not None else end
    body_lines = lines[:start] + lines[drop_end + 1 :]
    return metadata, "\n".join(body_lines)


def extract_tags_and_body(lines: list[str]) -> tuple[list[str], list[str]]:
    tags: list[str] = []
    body: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#import "):
            continue
        if stripped.startswith("#include "):
            continue
        if stripped.startswith("#show:"):
            continue
        if stripped.startswith("#status_tag("):
            continue
        if stripped.startswith("//"):
            continue
        tag_matches = re.findall(r"#tag\.([A-Za-z0-9_-]+)", line)
        if tag_matches and stripped.replace(" ", "") == "".join(f"#tag.{tag}" for tag in tag_matches):
            tags.extend(tag_matches)
            continue
        if tag_matches:
            tags.extend(tag_matches)
            line = re.sub(r"#tag\.[A-Za-z0-9_-]+", "", line).rstrip()
            if not line.strip():
                continue
        body.append(line)
    return sorted(set(tags)), body


def normalize_line(line: str, link_map: dict[str, dict[str, str]], link_prefix: str) -> str:
    heading = re.match(r"^(=+)\s+(.+)$", line)
    if heading:
        level = len(heading.group(1))
        text = re.sub(r"\s+<\d{10}>\s*$", "", heading.group(2)).strip()
        return f"{'#' * level} {replace_refs(text, link_map, link_prefix)}"
    return replace_refs(line, link_map, link_prefix)


def replace_refs(line: str, link_map: dict[str, dict[str, str]], link_prefix: str) -> str:
    def repl(match: re.Match[str]) -> str:
        ref = match.group(1)
        target = link_map.get(ref)
        if target is None:
            return f"@{ref}"
        return f"[{target['title']} @{ref}]({link_prefix}{target['filename']})"

    return re.sub(r"@(\d{10})", repl, line)


def render_frontmatter(
    metadata: str,
    *,
    source: str,
    tags: list[str],
    note_id: str | None,
    title: str | None,
) -> str:
    lines = ["+++"]
    if note_id:
        lines.append(f'id = "{toml_escape(note_id)}"')
    if title:
        lines.append(f'title = "{toml_escape(title)}"')
    lines.append(f'source = "{toml_escape(source)}"')
    if tags:
        lines.append("tags = [" + ", ".join(f'"{toml_escape(tag)}"' for tag in tags) + "]")
    metadata_lines = filter_reserved_frontmatter_keys(metadata)
    if metadata_lines:
        lines.extend(metadata_lines)
    lines.append("+++")
    frontmatter = "\n".join(lines)
    try:
        tomllib.loads("\n".join(lines[1:-1]))
    except tomllib.TOMLDecodeError as exc:
        raise MemoryDreamError(f"invalid normalized frontmatter for {source}: {exc}") from exc
    return frontmatter


def filter_reserved_frontmatter_keys(metadata: str) -> list[str]:
    lines: list[str] = []
    in_table = False
    for line in metadata.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("["):
            in_table = True
            lines.append(line.rstrip())
            continue
        if not in_table:
            key = top_level_toml_key(stripped)
            if key in RESERVED_FRONTMATTER_KEYS:
                continue
        lines.append(line.rstrip())
    return lines


def top_level_toml_key(stripped_line: str) -> str | None:
    if stripped_line.startswith('"'):
        escaped = False
        chars: list[str] = []
        for char in stripped_line[1:]:
            if escaped:
                chars.append(char)
                escaped = False
                continue
            if char == "\\":
                escaped = True
                continue
            if char == '"':
                rest = stripped_line[len(chars) + 2 :].lstrip()
                return "".join(chars) if rest.startswith("=") else None
            chars.append(char)
        return None
    if stripped_line.startswith("'"):
        end = stripped_line.find("'", 1)
        if end == -1:
            return None
        rest = stripped_line[end + 1 :].lstrip()
        return stripped_line[1:end] if rest.startswith("=") else None
    match = re.match(r"^([A-Za-z0-9_-]+)\s*=", stripped_line)
    return match.group(1) if match else None


def iso_now() -> str:
    return datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds")
